website/music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    path('', views.index, name='index'),

    path('<int:album_id>/', views.detail, name='detail'),

]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

website/music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return(self.album_title + ' - ' + self.artist)

class Song(models.Model):
    album =models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return(self.song_title)

website/music/views.py
from .models import Album, Song
from django.shortcuts import render, get_object_or_404

def index(request):
    all_albums = Album.objects.all()
    context = {
        'all_albums' : all_albums,
    }
    return render(request,'music/index.html', context)

def detail(request, album_id):
    album = get_object_or_404(Album,pk=album_id)
    return render(request, 'music/detail.html', {'album': album})

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except(KeyError, Song.DoesNotExist):
        return render(request,'music/detail.html', {
            'album' : album,
            'error_message': "You did not select valid song"
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
    return render(request, 'music/detail.html', {'album' : album})

website/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ZigZag</title>
</head>

{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel = "stylesheet" type="text/css" href="{% static 'music/style.css' %}" />

<nav class="navbar navbar-inverse">
    <div class = "container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}" >ZigZag</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                        Albums
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Songs
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group" >
                     <input class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">

                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Add Album
                    </a>
                </li>
                 <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>

            </ul>

        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

website/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="#">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="#" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

website/music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}
{% block body %}
<div class="albums-container container-fluid">
        <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>Albums</h3>
        </div>
        {% if all_albums %}
            {% for album in all_albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="#" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>

            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="#">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}